Algoritmo "Area de um quadrado"
// Disciplina   : [Lógica de Programação com visualg]
// Professor   : Jailson
// Descrição   : Um algoritímo que calcula a area de um quadrado
// Autor(a)    : Hugo
// Data atual  : 28/08/2024
Var
// Seção de Declarações das variáveis 
lado: real
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe o valor de um dos lados: ")
leia(lado)
escreval("informe o valor de outro lado: ")

Fimalgoritmo